# -*- coding: utf-8 -*-
"""carga_mental_lao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NazZBFv4kiHYdeDaijzH61bauL9iwM32
"""

import streamlit as st
from datetime import date, datetime, time # Importar datetime y time
import uuid
import locale
import json # Necesario para guardar y cargar datos
import os # Necesario para verificar si el archivo existe
import pandas as pd

# --- CONFIGURACIÓN DE LA PERSISTENCIA ---
# Usaremos un archivo JSON para almacenar datos y configuración.
TASKS_FILE = "tasks_data.json"

# --- CONFIGURACIÓN DEL IDIOMA (MÁS ROBUSTA) ---
# Intentamos establecer el locale para que las fechas se muestren en español.
locales_to_try = ['es_ES.UTF-8', 'es_ES.utf8', 'es_ES', 'es']
for loc in locales_to_try:
    try:
        locale.setlocale(locale.LC_TIME, loc)
        break
    except locale.Error:
        continue

# --- MAPAS DE TRADUCCIÓN MANUAL DE SEGURIDAD ---
# Se usan si el setlocale falla y strftime devuelve nombres en inglés.
SPANISH_MONTHS = {
    "January": "Enero", "February": "Febrero", "March": "Marzo", "April": "Abril",
    "May": "Mayo", "June": "Junio", "July": "Julio", "August": "Agosto",
    "September": "Septiembre", "October": "Octubre", "November": "Noviembre", "December": "Diciembre"
}

SPANISH_DAYS = {
    "Monday": "Lunes", "Tuesday": "Martes", "Wednesday": "Miércoles",
    "Thursday": "Jueves", "Friday": "Viernes", "Saturday": "Sábado", "Sunday": "Domingo"
}

def format_date_in_spanish(date_obj):
    """
    Formatea la fecha a español de manera segura (DíaSemana, Día de Mes de Año).
    """
    date_str = date_obj.strftime("%A, %d de %B de %Y")

    # Capitalizar la primera letra (Día de la semana)
    date_str = date_str.capitalize()

    # Traducción manual de seguridad si el locale falló
    for en, es in SPANISH_DAYS.items():
        date_str = date_str.replace(en, es).replace(en.lower(), es.lower())

    for en, es in SPANISH_MONTHS.items():
        date_str = date_str.replace(en, es).replace(en.lower(), es.lower())

    return date_str

# --- CONFIGURACIÓN DE LA PÁGINA ---
st.set_page_config(
    page_title="Organizador de Tareas: Carga Mental Cero",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- ESTILOS CSS PERSONALIZADOS ---

CAPTION_STYLE = """
<style>
/* Estilo para los subtítulos de las listas de tareas y calendario, forzando color negro */
div[data-testid="stCaptionContainer"] {
    color: #000000 !important;
}
</style>
"""
st.markdown(CAPTION_STYLE, unsafe_allow_html=True)


# --- CONSTANTES DE CATEGORÍA Y ESTILOS ---
CATEGORIES = {
    "🔴 Urgente": {"color": "#FF4B4B", "label": "Urgente"},      # Rojo
    "🟠 Importante": {"color": "#FFA500", "label": "Importante"},  # Naranja
    "🟡 Pendiente": {"color": "#FFD700", "label": "Pendiente"}   # Amarillo/Dorado
}

# --- FUNCIONES DE CARGA/GUARDADO DE DATOS (PERSISTENCIA) ---

def load_tasks():
    """Carga las tareas y la configuración desde el archivo JSON si existe."""
    default_config = {"reminder_time": time(18, 0)} # Por defecto 6:00 PM (18:00)

    if os.path.exists(TASKS_FILE):
        try:
            with open(TASKS_FILE, 'r') as f:
                data = json.load(f)

                tasks = data.get("tasks", [])
                config = data.get("config", {})

                # Convertir las cadenas de fecha ISO de vuelta a objetos date en las tareas
                for task in tasks:
                    if task["date"]:
                        task["date"] = date.fromisoformat(task["date"])

                # Convertir la cadena de tiempo a objeto time en la configuración
                if "reminder_time" in config and isinstance(config["reminder_time"], str):
                    h, m = map(int, config["reminder_time"].split(':'))
                    config["reminder_time"] = time(h, m)
                else:
                    config["reminder_time"] = default_config["reminder_time"]

                return tasks, config
        except json.JSONDecodeError:
            st.warning("El archivo de datos está corrupto. Se ha iniciado con una lista vacía y configuración por defecto.")
            return [], default_config

    return [], default_config

def save_tasks():
    """Guarda las tareas y la configuración en el archivo JSON."""

    tasks_to_save = []
    # 1. Pre-procesar tareas (date -> string)
    for task in st.session_state.tasks:
        task_copy = task.copy()
        if task_copy["date"]:
            task_copy["date"] = task_copy["date"].isoformat()
        tasks_to_save.append(task_copy)

    # 2. Pre-procesar configuración (time -> string)
    config_to_save = st.session_state.config.copy()
    if "reminder_time" in config_to_save:
        config_to_save["reminder_time"] = config_to_save["reminder_time"].strftime("%H:%M")

    data_to_save = {
        "tasks": tasks_to_save,
        "config": config_to_save
    }

    with open(TASKS_FILE, 'w') as f:
        json.dump(data_to_save, f, indent=4)

# --- INICIALIZACIÓN DEL ESTADO DE SESIÓN ---
# Inicializa tareas y configuración (incluida la hora de recordatorio)
if 'tasks' not in st.session_state or 'config' not in st.session_state:
    loaded_tasks, loaded_config = load_tasks()
    st.session_state.tasks = loaded_tasks
    st.session_state.config = loaded_config

# --- FUNCIONES AUXILIARES ---

def set_reminder_time(new_time):
    """Actualiza la hora del recordatorio en la configuración y guarda."""
    st.session_state.config["reminder_time"] = new_time
    save_tasks()

def remove_task(task_id):
    """Elimina una tarea por su ID y guarda los cambios."""
    # El task_id debe ser un string válido (UUID)
    st.session_state.tasks = [task for task in st.session_state.tasks if task["id"] != task_id]
    save_tasks() # Guardar después de eliminar

def add_task(description, category_key, due_date):
    """Agrega una nueva tarea y guarda los cambios."""
    if description:
        category_name = CATEGORIES[category_key]["label"]

        new_task = {
            "id": str(uuid.uuid4()),
            "description": description,
            "category": category_name,
            "category_key": category_key,
            "date": due_date # date object or None
        }
        st.session_state.tasks.append(new_task)
        st.session_state.new_task_description = ""
        st.success("¡Tarea agregada exitosamente!")
        save_tasks() # Guardar después de agregar
    else:
        st.error("La descripción de la tarea no puede estar vacía.")

def update_task_date(task_id, new_date):
    """Actualiza la fecha de una tarea por su ID."""
    for i, t in enumerate(st.session_state.tasks):
        if t["id"] == task_id:
            st.session_state.tasks[i]["date"] = new_date
            save_tasks()
            return True
    return False

def move_task_to_calendar_callback(task_id):
    """
    Callback ejecutado al presionar 'Mover a Calendario'.
    Lee la fecha del st.date_input asociado y actualiza la tarea.
    """
    date_key = f"popover_date_{task_id}"
    new_date = st.session_state.get(date_key)

    if new_date:
        if update_task_date(task_id, new_date):
            pass

# --- LÓGICA DE CLASIFICACIÓN ---

def get_tasks_by_status():
    """Clasifica las tareas en listas sin fecha y tareas con fecha (calendario)."""

    tasks_no_date = {data["label"]: [] for data in CATEGORIES.values()}
    tasks_with_date = []

    for task in st.session_state.tasks:
        cat_label = CATEGORIES[task["category_key"]]["label"]
        if task["date"] is None:
            tasks_no_date[cat_label].append(task)
        else:
            tasks_with_date.append(task)

    tasks_with_date.sort(key=lambda x: x["date"])

    return tasks_no_date, tasks_with_date

# --- UI: ENTRADA DE TAREAS (SIDEBAR) ---

with st.sidebar:
    st.title("➕ Organiza tu Carga Mental")
    st.markdown("---")

    st.header("Configuración de Recordatorio")
    st.warning(
        "**NOTA:** Streamlit no puede enviar recordatorios externos (emails/notificaciones). "
        "Esta opción guarda tu hora preferida para que puedas revisar la app diariamente."
    )

    # UI para establecer la hora del recordatorio
    current_reminder_time = st.session_state.config.get("reminder_time", time(18, 0))

    # Input de tiempo
    new_reminder_time = st.time_input(
        "Hora diaria de Recordatorio (Hora Local):",
        value=current_reminder_time,
        key="reminder_time_input"
    )

    # Actualizar la hora si ha cambiado
    if new_reminder_time != current_reminder_time:
        set_reminder_time(new_reminder_time)

    st.markdown("---")

    st.header("Nueva Tarea")

    # 1. Descripción de la tarea
    description = st.text_input(
        "1. Describe la tarea:",
        key="new_task_description",
        placeholder="Ejemplo: Preparar informe mensual"
    )

    # 2. Nivel de Urgencia
    category = st.radio(
        "2. Nivel de urgencia:",
        options=CATEGORIES.keys(),
        index=1, # Por defecto 'Importante'
        horizontal=True,
        key="new_task_category"
    )

    # 3. Fecha específica (Opcional)
    has_date = st.checkbox("¿Tiene fecha específica?", key="has_date_checkbox")
    due_date = None
    if has_date:
        due_date = st.date_input("3. Elige la fecha:", min_value=date.today(), key="new_task_date")

    # Botón para agregar la tarea
    st.button(
        "Guardar Tarea",
        on_click=add_task,
        args=(description, category, due_date if has_date else None),
        type="primary",
        use_container_width=True
    )
    st.markdown("---")
    st.markdown("🤖 **Objetivo:** Disminuir tu carga mental al visualizar y clasificar tus compromisos.")

# --- UI: PANTALLA PRINCIPAL ---

# Obtener tareas clasificadas
tasks_no_date, tasks_with_date = get_tasks_by_status()

st.title("📅 Panel de Tareas")

# --- WIDGET DE ESTADO DEL RECORDATORIO ---
now = datetime.now()
current_time_readable = now.strftime("%H:%M")
reminder_time_obj = st.session_state.config["reminder_time"]
reminder_time_str = reminder_time_obj.strftime("%H:%M")

# Comprobar si es hora de recordatorio (dentro de la misma hora)
# Se comprueba si la hora actual es IGUAL o MAYOR a la hora de recordatorio.
is_reminder_time = now.hour == reminder_time_obj.hour and now.minute >= reminder_time_obj.minute

if is_reminder_time:
    reminder_status_icon = "🔔"
    reminder_message = f"**¡HORA DE REVISIÓN!** Son las {current_time_readable}. Revisa tu lista de tareas pendientes para asignar fechas."
    reminder_box_style = "background-color: #FFFFAA; border: 2px solid #FFA500; padding: 10px; border-radius: 8px; margin-bottom: 20px;"
else:
    reminder_status_icon = "🕒"
    reminder_message = f"Recordatorio de revisión activo: Todos los días a las **{reminder_time_str}** (Hora Local). Hora actual: {current_time_readable}."
    reminder_box_style = "background-color: #e6f7ff; border: 1px solid #99d6ff; padding: 10px; border-radius: 8px; margin-bottom: 20px;"

st.markdown(
    f'<div style="{reminder_box_style}">{reminder_status_icon} {reminder_message}</div>',
    unsafe_allow_html=True
)
# --- FIN DEL WIDGET ---

# --- SECCIÓN 1: TAREAS POR ASIGNAR (LISTAS POR CATEGORÍA) ---

st.header("Lista de Tareas Pendientes (Sin Fecha Asignada)")
st.caption("Estas tareas necesitan que les asignes una fecha para moverlas al calendario.")

# Crear tres columnas para las listas de tareas
col1, col2, col3 = st.columns(3)

def display_task_list(column, category_label, tasks):
    """Muestra una lista de tareas en una columna con el estilo de su categoría."""
    category_data = next((v for k, v in CATEGORIES.items() if v["label"] == category_label), None)
    color = category_data["color"] if category_data else "#CCCCCC"

    with column:
        # Estilo para el encabezado de la lista
        st.markdown(
            f"""
            <div style="background-color: {color}; padding: 10px; border-radius: 8px 8px 0 0; color: white; text-align: center; font-weight: bold;">
                {category_label.upper()} ({len(tasks)})
            </div>
            """,
            unsafe_allow_html=True
        )

        if not tasks:
            st.info("¡No hay tareas en esta categoría!")

        for task in tasks:
            # Contenedor principal de la tarea
            st.markdown(
                f"""
                <div style="border: 1px solid {color}; border-radius: 0 0 8px 8px; margin-top: -1px; padding: 10px; display: flex; justify-content: space-between; align-items: center;">
                    <span style="flex-grow: 1; margin-right: 10px;">{task['description']}</span>
                </div>
                """,
                unsafe_allow_html=True
            )

            # Contenedor para los botones (popover y eliminar)
            col_popover, col_btn_del = st.columns([4, 1])

            with col_btn_del:
                # Botón de eliminar - **CORRECCIÓN APLICADA AQUÍ**
                st.button(
                    "🗑️",
                    key=f"del_no_date_{task['id']}",
                    on_click=lambda task_id=task['id']: remove_task(task_id), # Usa lambda para forzar la captura del ID
                    help="Eliminar tarea"
                    # Eliminado args=(task['id'],)
                )

            with col_popover:
                # Popover para mover al calendario
                with st.popover("📅 Asignar fecha", use_container_width=True):
                    # Input de fecha, cuyo valor se guarda en el estado de sesión
                    st.date_input(
                        "Selecciona una fecha para esta tarea:",
                        min_value=date.today(),
                        key=f"popover_date_{task['id']}"
                    )

                    # Botón que llama al callback para leer la fecha del input y mover la tarea
                    st.button(
                        "Mover a Calendario",
                        key=f"move_to_cal_{task['id']}",
                        on_click=move_task_to_calendar_callback,
                        args=(task['id'],),
                        type="primary",
                        use_container_width=True
                    )

# Mostrar las tres listas
display_task_list(col1, "Urgente", tasks_no_date["Urgente"])
display_task_list(col2, "Importante", tasks_no_date["Importante"])
display_task_list(col3, "Pendiente", tasks_no_date["Pendiente"])

st.markdown("---")

# --- SECCIÓN 2: CALENDARIO (TAREAS ASIGNADAS) ---

st.header("🗓️ Calendario")
# Se incluye el subtítulo dinámico con el color de letra forzado a negro
st.caption(f"Tienes **{len(tasks_with_date)}** tareas programadas.")

if not tasks_with_date:
    st.info("¡No tienes tareas con fecha específica aún! Agrégalas o asígnales una fecha desde las listas.")
else:
    # Agrupar las tareas por fecha
    tasks_by_date = {}
    for task in tasks_with_date:
        # USANDO LA FUNCIÓN DE FORMATO EN ESPAÑOL DE SEGURIDAD
        date_str = format_date_in_spanish(task["date"])
        if date_str not in tasks_by_date:
            tasks_by_date[date_str] = []
        tasks_by_date[date_str].append(task)

    for date_str, tasks in tasks_by_date.items():
        # Ordenar tareas dentro del día por nivel de urgencia para destacar la más importante
        tasks.sort(key=lambda t: list(CATEGORIES.keys()).index(t['category_key']))
        top_color = CATEGORIES[tasks[0]['category_key']]['color']

        # Expander (el contenedor del día)
        with st.expander(f"**{date_str}** ({len(tasks)} Tareas)", expanded=True):
            # Inyectar CSS para el borde del expander
            st.markdown(
                f'<style>.stExpanderDetails {{ border-left: 5px solid {top_color}; padding-left: 10px; }}</style>',
                unsafe_allow_html=True
            )
            for task in tasks:
                color = CATEGORIES[task["category_key"]]["color"]

                # Diseño de tarjeta para cada tarea en el calendario
                col_desc, col_complete, col_btn_del = st.columns([4, 1, 1])

                with col_desc:
                    # Tarjeta de descripción con barra lateral de color
                    st.markdown(
                        f"""
                        <div style="background-color: #f0f2f6; border-left: 5px solid {color}; padding: 10px; margin-bottom: 5px; border-radius: 4px; display: flex; align-items: center;">
                            <strong style="margin-right: 10px;">{task['category_key'].split(' ')[0]}</strong>
                            <span>{task['description']}</span>
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

                # --- BOTÓN: MARCAR COMO COMPLETADA - **CORRECCIÓN APLICADA AQUÍ** ---
                with col_complete:
                    st.button(
                        "✅",
                        key=f"complete_{task['id']}",
                        on_click=lambda task_id=task['id']: remove_task(task_id), # Usa lambda para forzar la captura del ID
                        help="Marcar como realizada (Completar)",
                        type="secondary"
                        # Eliminado args=(task['id'],)
                    )

                with col_btn_del:
                    # --- BOTÓN: ELIMINAR TAREA - **CORRECCIÓN APLICADA AQUÍ** ---
                    st.button(
                        "🗑️",
                        key=f"del_date_{task['id']}",
                        on_click=lambda task_id=task['id']: remove_task(task_id), # Usa lambda para forzar la captura del ID
                        help="Eliminar tarea"
                        # Eliminado args=(task['id'],)
                    )